services:
  firovm:
    image: satangtech/firovm-poa:d98e284274c1e95bb36ed61d1566214b7148f698
    tty: true
    stdin_open: true
    command: -connect=0
    volumes:
      - ./.firovm:/firovm
    ports:
      - 1234:1234
      - 11000:11000

  it-test:
    build: .
    tty: true
    stdin_open: true
    depends_on:
      - firovm
